=== osawa-koki/XML-schema-definition.cs/src/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="person">
  <xsd:complexType>
    <xsd:sequence>

      <xsd:element name="name" type="xsd:string" />
      <xsd:element name="age" type="xsd:date" />
      <xsd:element name="sex">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Male" />
            <xsd:enumeration value="Female" />
            <xsd:enumeration value="Other" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="height" type="xsd:nonNegativeInteger"></xsd:element>
      <xsd:element name="weight" type="xsd:nonNegativeInteger"></xsd:element>

      <xsd:element name="educational-background">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="school" minOccurs="0"  maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="name" type="xsd:string" />
                  <xsd:element name="majoring" type="xsd:string" nillable="true" minOccurs="0" />
                  <xsd:element name="address" type="xsd:string" />
                  <xsd:element name="entering-date" type="xsd:gYearMonth" />
                  <xsd:element name="graduating-date" type="xsd:gYearMonth" />
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name="professional-background">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="work" minOccurs="0"  maxOccurs="unbounded">
              <xsd:complexType>
                <xsd:sequence>
                  <xsd:element name="name" type="xsd:string" />
                  <xsd:element name="role" type="xsd:string" />
                  <xsd:element name="address" type="xsd:string" />
                  <xsd:element name="entering-date" type="xsd:gYearMonth" />
                  <xsd:element name="quitting-date" type="xsd:gYearMonth" nillable="true" />
                </xsd:sequence>
              </xsd:complexType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>

      <xsd:element name="comment" type="xsd:string"></xsd:element>

    </xsd:sequence>
  </xsd:complexType>
</xsd:element>
</xsd:schema>

=== osawa-koki/XML-schema-definition.cs/src/config.xml
<?xml version="1.0" encoding="utf-8"?>

<person xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">

  <name>osawa-koki</name>
  <age>1998-10-25</age>
  <sex>Male</sex>
  <height>182</height>

  <educational-background>
    <school>
      <name>越谷北高等学校</name>
      <address>埼玉県</address>
      <entering-date>2014-04</entering-date>
      <graduating-date>2017-03</graduating-date>
    </school>
    <school>
      <name>明治大学</name>
      <majoring>会計学</majoring>
      <address>東京都</address>
      <entering-date>2017-04</entering-date>
      <graduating-date>2022-03</graduating-date>
    </school>
  </educational-background>

  <professional-background>
    <work>
      <name>株式会社ソフトクリエイトホールディングス</name>
      <role>セキュリティエンジニア</role>
      <address>東京都</address>
      <entering-date>2022-04</entering-date>
      <quitting-date>2023-03</quitting-date>
    </work>
    <work>
      <name>SecureNavi株式会社</name>
      <role>Webエンジニア(フロントエンド・バックエンド・インフラ)</role>
      <address>東京都</address>
      <entering-date>2023-04</entering-date>
      <quitting-date xsi:nil="true"></quitting-date>
    </work>
  </professional-background>

  <comment>🐙 タコさんマークのエンジニア 🐙</comment>

</person>
